# Generated by Django 5.0 on 2023-12-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=55)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Makeup", "Makeup"),
                            ("Haircare", "Haircare"),
                            ("Skincare", "Skincare"),
                            ("Appliances", "Appliances"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("desc", models.TextField(max_length=255)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="pics")),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glimmerapp.product",
                    ),
                ),
            ],
        ),
    ]
