# Generated by Django 5.0 on 2023-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glimmerapp", "0002_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="qty",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
