# Generated by Django 5.0 on 2023-12-16 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("glimmerapp", "0003_wishlist_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="qty",
        ),
    ]
